### ISSUE TITLE
Error on pull API `too_long_frame_exception`

### ISSUE THREAD

**Issue by sw-jung** [sw-jung/kibana_notification_center#6]
```
[too_long_frame_exception] An HTTP line is larger than 4096 bytes. :: {"path":"/notification-2017.10.07%2Cnotification-2017.10.07%2Cnotification-2017.10.07%2Cnotification-2017.10.07%2Cnotification-2017.10.07%2Cnotification-2017.10.07%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.08%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.09%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.10%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.11%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.12%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.13%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.14%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.15%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.16%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.17%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.18%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.19%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.20%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.21%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.22%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.23%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.24%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.25%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.26%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.27%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.28%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.29%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.30%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.10.31%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.01%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.02%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.03%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.04%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.05%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.06%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.07%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.08%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09%2Cnotification-2017.11.09/notification/_search","query":{"size":100,"ignore_unavailable":true},"body":"{\"query\":{\"bool\":{\"must\":[{\"range\":{\"timestamp\":{\"gt\":1507367558098}}}]}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"too_long_frame_exception\",\"reason\":\"An HTTP line is larger than 4096 bytes.\"}],\"type\":\"too_long_frame_exception\",\"reason\":\"An HTTP line is larger than 4096 bytes.\"},\"status\":400}"}
    at respond (C:\Users\kjss1\dev\github\kibana\node_modules\elasticsearch\src\lib\transport.js:295:15)
    at checkRespForFailure (C:\Users\kjss1\dev\github\kibana\node_modules\elasticsearch\src\lib\transport.js:254:7)
    at HttpConnector.<anonymous> (C:\Users\kjss1\dev\github\kibana\node_modules\elasticsearch\src\lib\connectors\http.js:159:7)
    at IncomingMessage.bound (C:\Users\kjss1\dev\github\kibana\node_modules\elasticsearch\node_modules\lodash\dist\lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by sw-jung** [comment]
Cause:
Below function named `parsePartitionUnit`, returns the unexpected unit when the bounds are beyond the date.

```javascript
const testUnits = [
  'milliseconds',
  'seconds',
  'minutes',
  'hours',
  'days',
  'weeks',
  'months',
  'quarters',
  'years'
];
export function parsePartitionUnit(index) {
  if (!hasDateExpression(index)) {
    return;
  }

  const now = moment();
  return find(testUnits, unit => {
    return parseWithTimestamp(index, now) !== parseWithTimestamp(index, now.add(1, unit));
  });
};
```

Need backports

**Comment by sw-jung** [comment]
Backports:
v5.5: 9b44e3a16366b24c10944fe8fe691fcc512636f1
v5.4: c7d9c22f75e75ed93583fc312225a71088d82616
